name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [auth-service, blog-service, comment-service, profile-service]

    steps:
      - name: Checkout Code
      
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Dependencies
        run: npm ci
        working-directory: ./${{ matrix.service }}

      - name: Run Tests
        run: npm test
        working-directory: ./${{ matrix.service }}

      - name: Build Docker Image
        run: docker build -t ${{ matrix.service }} ./${{ matrix.service }}
